"""sections

Revision ID: 2d7f213ee21c
Revises: d5c54b696d8f
Create Date: 2025-10-13 23:55:51.348884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d7f213ee21c'
down_revision = 'd5c54b696d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_lecture_course_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_lecture_section_id', 'sections', ['section_id'], ['id'])
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lectures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('fk_lecture_section_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_lecture_course_id'), 'courses', ['course_id'], ['id'])
        batch_op.drop_column('section_id')

    op.drop_table('sections')
    # ### end Alembic commands ###
