"""rating

Revision ID: d5c54b696d8f
Revises: fcc5452fe7b7
Create Date: 2025-10-13 22:35:00.169330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c54b696d8f'
down_revision = 'fcc5452fe7b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('apikey',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)

    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.drop_column('watched_seconds')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watched_seconds', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('apikey',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.drop_table('rating')
    # ### end Alembic commands ###
