"""instructor

Revision ID: f75842ebff33
Revises: c58bfdbcf497
Create Date: 2025-10-12 17:55:10.985851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75842ebff33'
down_revision = 'c58bfdbcf497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('library_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('library_id',
               existing_type=sa.String(length=250),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.drop_table('instructor')
    # ### end Alembic commands ###
