"""instructor

Revision ID: fcc5452fe7b7
Revises: f75842ebff33
Create Date: 2025-10-12 18:05:10.142470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc5452fe7b7'
down_revision = 'f75842ebff33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.alter_column('total_earnings',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instructor', schema=None) as batch_op:
        batch_op.alter_column('total_earnings',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
